import "./globals.css";
import { NavLinks } from "./ui/NavLinks";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavLinks />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
